Add base code
GasBarrel/GasBarrel pull request #2
Opened 2023-05-18 16:20 UTC by freya022

2023-05-18 17:10 UTC, RGBCube commented
I think we should just do a `config.json5`

2023-05-18 17:10 UTC, RGBCube commented
I think we should just do a `config.json5`

2023-05-19 09:21 UTC, Xirado requested changes

2023-05-19 09:44 UTC, TopiSenpai requested changes

2023-05-19 09:44 UTC, TopiSenpai commented on src/main/kotlin/io/github/gasbarrel/commands/slash/SlashPing.kt
> +            description = "Pong !"
```suggestion
            description = "Pong!"
```

2023-05-19 09:44 UTC, TopiSenpai commented on src/main/kotlin/io/github/gasbarrel/Main.kt
> +            logger.info( "Loading production logback config")
```suggestion
            logger.info("Loading production logback config")
```

2023-05-19 09:44 UTC, TopiSenpai commented on src/main/kotlin/io/github/gasbarrel/Main.kt
> +            logger.info( "Loading test logback config")
```suggestion
            logger.info("Loading test logback config")
```

2023-05-19 09:44 UTC, TopiSenpai commented on src/main/kotlin/io/github/gasbarrel/commands/slash/SlashPing.kt
> +@CommandMarker //Shut up IJ
```suggestion
@CommandMarker // Shut up IJ
```

2023-05-19 09:44 UTC, TopiSenpai commented on src/main/kotlin/io/github/gasbarrel/JDAService.kt
> +            setActivity(Activity.playing("with a cigarette"))
```suggestion
            setActivity(Activity.playing("with a cigarette 🚬"))
```

2023-05-19 10:08 UTC, Xirado requested changes

2023-05-19 10:52 UTC, RGBCube commented on src/main/kotlin/io/github/gasbarrel/Data.kt
> +    private val botFolder: Path = Path(System.getProperty("user.home"), "Bots", "GasBarrel").validate("Bot folder")
I think we should do `.config/GasBarrel` on Linux, `%APPDATA%\GasBarrel` on Windows and so on

2023-05-19 10:56 UTC, RGBCube commented on src/main/kotlin/io/github/gasbarrel/Data.kt
> +    private val botFolder: Path = Path(System.getProperty("user.home"), "Bots", "GasBarrel").validate("Bot folder")
We can do this by
```kt
val configFolder = System.getenv("XDG_CONFIG_HOME") ?: "${System.getProperty("user.home")}/.config"
```

2023-05-19 17:50 UTC, Xirado approved these changes

2023-05-19 18:22 UTC, TopiSenpai submitted a review, later dismissed
kotlin bad, can't approve, rewrite in go

2023-05-19 19:44 UTC, Xirado approved these changes

2023-05-19 19:53 UTC, merged